/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jodoi.mybatislogback;

import lombok.extern.slf4j.Slf4j;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;

import java.util.List;

@Slf4j
public class App {

    public static void main(String[] args) {
        MySqlSessionFactory mySqlSessionFactory = new MySqlSessionFactory();
        SqlSessionFactory sqlSessionFactory = mySqlSessionFactory.build();
        try (SqlSession sqlSession = sqlSessionFactory.openSession()) {
            sqlSession.selectOne("jodoi.mybatislogback.mapper.UserMapper.insert");
            sqlSession.insert("jodoi.mybatislogback.mapper.UserMapper.failedInsert", "thisisakey");
            List<String> name = sqlSession.selectList("jodoi.mybatislogback.mapper.UserMapper.select");
            name.forEach(n -> System.out.println("Hello world! " + n));
        } catch (Exception e) {
//            log.error("e.getMessage(): " + e.getMessage());
//            log.error("e.getCause().getMessage(): " + e.getCause().getMessage());
            log.error("ERROR: Pass Throwable as a second argument", e);
            log.warn("WARN: Pass Throwable as a second argument", e);
        }
    }
}
